### ISSUE TITLE
alpine or ubuntu

### ISSUE THREAD

**Issue by amalagaura** [Trunkplatform/docker-geminabox#1]
I checked the quay image you are using and it uses Ubuntu, not Alpine like the readme says:

https://quay.io/repository/trunk/ruby-base?tag=1.4

**Comment by nagliyvred** [comment]
Thanks @amalagaura for pointing it out - it is indeed Ubuntu 14.04 https://hub.docker.com/r/cloudgear/ruby/ 
I've updated the readme

**Comment by amalagaura** [comment]
Cool, your image is still very useful. Also now that Ubuntu Xenial has Ruby 2.3 as a default it could make for good images too.
